---
title: "Homework3_IDS"
author: "justyn koenig"
date: "10/17/2021"
output:
  pdf_document: default
  html_document: default
---

# Question 1 

```{r}
set.seed(12) # to be reproducible
A = matrix(data = runif(n = 1:500), nrow = 50, ncol = 10)
colnames(A) = paste("lake", 1:10, sep = "_")
data1 <- data
data1

```

```{r}
for(i in 1:ncol(A)){
  print(mean(A[, i]))
}

colMeans(A)

```

# Question 2 

```{r}
x = array(1:27, dim = c(3, 3, 3))
apply(X = x, MARGIN = c(1, 2), 
      FUN = paste, collapse = ", ")

```

```{r}
x = array(1:27, dim = c(3, 3, 3))
y = array(0, dim=c(3, 3, 3))
for (i in 1:3){
  for (j in 1:3) {
    for (k in 1:3) {
      y[i,j,] = paste(x[i,j,],collapse = ", ")
    }
  }
}
y

```

# Question 3

```{r}
N <- 30
for (i in 1:30){
  N[1] = 0
  N[2] = 1
  N[i+2] = N[i]+N[i+1]
}
N

```

# Question 4 

```{r}
top105 = readLines("http://www.textfiles.com/music/ktop100.txt")
top105 = top105[-c(64, 65)] # missing No. 54 and 55

```

```{r}
pattern <- "^[0-9]*\\.*[0-9]\\."
library("stringr")
A = str_extract(top105,pattern)
A
B = grep("^[0-9]*\\.*[0-9]\\.*[0-9]", A, value =TRUE)
B

```

# Question 5 

```{r}
C = as.numeric(B)
is.numeric(C)
D <- gregexpr(pattern = "(\\d{1,3})", text = C)
E = regmatches(C, D)
C[duplicated(C, incomparables =FALSE)]

```


